export {Login as ScreenLogin} from "./login"
export { Register as ScreenRegister } from "./Register"
export { Home as Home } from "./Home"
export { Informacoes as Informacoes } from "./Informacoes"
export {Perfil as Perfil} from "./Perfil"
export {LocationMap as ScreenLocation} from './LocationMap'
//pagina dos doces 
export { Cookie as Cookie } from "../screens/Doces/cookie"
export { Biscoito as Biscoito } from "../screens/Doces/Biscoito"
export { Brigadeiro as Brigadeiro } from "../screens/Doces/Brigadeiro"
export { Brownie as Brownie } from "../screens/Doces/Brownie"
export { ConeReachado as ConeRecheado } from "../screens/Doces/ConeRecheado"
export { Cupcake as Cupcake } from "../screens/Doces/Cupcake"
export { Donuts as Donuts } from "../screens/Doces/Donuts"
export { BolodePote as BolodePote } from "../screens/Doces/BolodePote"